<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Neko" failures="1" tests="4" name="tModule Test" time="0.108" errors="0" timestamp="2021-04-28T21:54:10 ICT">
  <testcase classname="poro.module.db.data.PhongTest" name="InsertPhong" time="0.024"/>
  <testcase classname="poro.module.db.data.PhongTest" name="SelectAllphong" time="0.013"/>
  <testcase classname="poro.module.db.data.PhongTest" name="SelectByIdPhong" time="0.037"/>
  <testcase classname="poro.module.db.data.PhongTest" name="UpdatePhong" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at poro.module.db.data.PhongTest.UpdatePhong(PhongTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UpdatePhong -->
</testsuite> <!-- tModule Test -->
