<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Neko" failures="1" tests="1" name="Default test" time="13.22" errors="0" timestamp="2021-05-03T11:05:19 ICT">
  <testcase classname="poro.gui.MuonPhongJDialogTest" name="muon201Test" time="3.826">
    <failure type="java.lang.AssertionError" message="expected [3/05/2021 11:05:00] but found [03/05/2021 11:05:00]">
      <![CDATA[java.lang.AssertionError: expected [3/05/2021 11:05:00] but found [03/05/2021 11:05:00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.gui.MuonPhongJDialogTest.muon201Test(MuonPhongJDialogTest.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- muon201Test -->
  <testcase classname="poro.gui.MuonPhongJDialogTest" name="xacNhanMuonTest" time="0.0">
    <ignored/>
  </testcase> <!-- xacNhanMuonTest -->
  <testcase classname="poro.gui.MuonPhongJDialogTest" name="errorFromSvTest" time="0.0">
    <ignored/>
  </testcase> <!-- errorFromSvTest -->
  <testcase classname="poro.gui.MuonPhongJDialogTest" name="errorFromTest" time="0.0">
    <ignored/>
  </testcase> <!-- errorFromTest -->
  <testcase classname="poro.gui.MuonPhongJDialogTest" name="muonOkSvTest" time="0.0">
    <ignored/>
  </testcase> <!-- muonOkSvTest -->
</testsuite> <!-- Default test -->
