<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-21T13:55:19 ICT" name="Default suite" finished-at="2021-04-21T13:55:19 ICT" duration-ms="145">
    <groups>
    </groups>
    <test started-at="2021-04-21T13:55:19 ICT" name="Default test" finished-at="2021-04-21T13:55:19 ICT" duration-ms="145">
      <class name="poro.module.FileManagerTest">
        <test-method signature="readObjectTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="readObjectTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="44" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [poro.module.db.data.TaiKhoan@c88a337] but found [poro.module.db.data.TaiKhoan@1de5f259]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [poro.module.db.data.TaiKhoan@c88a337] but found [poro.module.db.data.TaiKhoan@1de5f259]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.module.FileManagerTest.readObjectTest(FileManagerTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readObjectTest -->
        <test-method signature="readStringTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="readStringTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readStringTest -->
        <test-method signature="readTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="readTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readTest -->
        <test-method signature="writeObjectTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="writeObjectTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [poro.module.db.data.TaiKhoan@51e69659] but found [poro.module.db.data.TaiKhoan@47e2e487]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [poro.module.db.data.TaiKhoan@51e69659] but found [poro.module.db.data.TaiKhoan@47e2e487]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.module.FileManagerTest.writeObjectTest(FileManagerTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeObjectTest -->
        <test-method signature="writeStringTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="writeStringTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeStringTest -->
        <test-method signature="writeTest()[pri:0, instance:poro.module.FileManagerTest@7c83dc97]" started-at="2021-04-21T13:55:19 ICT" name="writeTest" finished-at="2021-04-21T13:55:19 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeTest -->
      </class> <!-- poro.module.FileManagerTest -->
=======
<testng-results ignored="2" total="3" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-21T14:28:06 ICT" name="Default suite" finished-at="2021-04-21T14:28:07 ICT" duration-ms="1218">
    <groups>
    </groups>
    <test started-at="2021-04-21T14:28:06 ICT" name="Default test" finished-at="2021-04-21T14:28:07 ICT" duration-ms="1218">
      <class name="poro.module.db.data.MuonPhongTest">
        <test-method signature="getListByPhongNoTest()[pri:0, instance:poro.module.db.data.MuonPhongTest@60015ef5]" started-at="2021-04-21T14:28:06 ICT" name="getListByPhongNoTest" finished-at="2021-04-21T14:28:07 ICT" duration-ms="1135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListByPhongNoTest -->
      </class> <!-- poro.module.db.data.MuonPhongTest -->
>>>>>>> 0828e9f9dd5ecb78730235eb544cd069251783f3
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
